markdown:     rdiscount
pygments:     true
paginate:     4
permalink:    /:categories/:title

title:        XBOOT - An extensible bootloader
url:          http://xboot.org
feed:         /atom.xml
author:
    name:     Jianjun Jiang
    email:    jerryjianjun@gmail.com
description:  "xboot, an extensible bootloader"

about:        "I am xboot.I love all kinds of design, attention to the Internet dynamic, dedicated web front development, learn UI and UED."
follow:
    github:   https://github.com/jerryjianjun
    twitter:  http://www.twitter.com/piznlin
description:  "PIZn's blog theme -- Black Cube Theme 1.0 "

style:        /css/style.css
blogName:     XBOOT
blogDesc:     An extensible bootloader.
